name: Deploy to Server

on: 
    push:
        branches: 
            - main

jobs: 
    deploy: 
        runs-on: ubuntu-latest

        env:
            SOLUTION_PATH: ./Showcase/Showcase.sln
            PROJECT_PATH: ./Showcase/Showcase.Web/Showcase.Web.csproj
            PUBLISH_PATH: ./Showcase.Web/bin/Release/net-8.0/linux-x64/publish/
            SERVER_PATH: /var/www/showcase/
            SENDGRID_SHOWCASE_KEY: ${{ secrets.SENDGRID_SHOWCASE_KEY }}
            RECAPTCHA_SHOWCASE_KEY: ${{ secrets.RECAPTCHA_SHOWCASE_KEY }}
            SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
            SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
            SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x
            
            - name: Restore Dependencies
              run: dotnet restore ${{ env.SOLUTION_PATH }}

            - name: Build and Publish
              run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 --self-contained false --configuration Release

            - name: Sync files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                server: ${{ env.SERVER_ADDRESS }}
                username: ${{ env.SERVER_USERNAME }}
                password: ${{ env.SERVER_PASSWORD }}
                local-dir: ${{ env.PUBLISH_PATH }}
                server-dir: ${{ env.SERVER_PATH }}
                protocol: ftps
                port: 22

            - name: Remotely Restart Showcase
              run: ssh -o StrictHostKeyChecking=no -p 22 -i ${{ env.SSH_PRIVATE_KEY }} ${{ env.SERVER_USERNAME }}@${{ env.SERVER_ADDRESS }} 'sudo systemctl restart showcase'