name: Deploy to Server

on: 
    push:
        branches: 
            - main

jobs: 
    deploy: 
        runs-on: ubuntu-latest

        env:
            SOLUTION_PATH: ./Showcase/Showcase.sln
            PROJECT_PATH: ./Showcase/Showcase.Web/Showcase.Web.csproj
            PUBLISH_PATH: ${{ github.workspace }}/Showcase/Showcase.Web/bin/Release/net8.0/linux-x64/publish/
            SERVER_PATH: /var/www/showcase/
            SENDGRID_SHOWCASE_KEY: ${{ secrets.SENDGRID_SHOWCASE_KEY }}
            RECAPTCHA_SHOWCASE_KEY: ${{ secrets.RECAPTCHA_SHOWCASE_KEY }}
            SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
            SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
            SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: 7.0.x
            
            - name: Restore Dependencies
              run: dotnet restore ${{ env.SOLUTION_PATH }}

            - name: Build and Publish
              run: dotnet publish ${{ env.PROJECT_PATH }} -r linux-x64 --self-contained false --configuration Release

            - name: Copy Files to Server
              uses: up9cloud/action-rsync@v1.4 
              env:
                HOST: ${{ env.SERVER_ADDRESS }}
                KEY: ${{ env.SSH_PRIVATE_KEY }}
                # PASSWORD: ${{env.SERVER_PASSWORD }} # it's less secure, using KEY instead
                TARGET: ${{ env.SERVER_PATH }}
        
                VERBOSE: true
                USER: ubuntu
                ARGS: -az --exclude=/.git/
                SSH_ARGS: '-p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
                SOURCE: ${{ env.PUBLISH_PATH }}
        
                PRE_SCRIPT: |
                  echo start at:
                  date -u
                POST_SCRIPT: "echo done at: && date -u"

            - name: Remotely Restart Showcase
              run: ssh -o StrictHostKeyChecking=no -v -p 22 -i "ssh_key" "${{ env.SERVER_USERNAME }}@${{ env.SERVER_ADDRESS }}" 'sudo systemctl restart showcase'