name: Deploy to Server

on: 
    push:
        branches: 
            - main

jobs: 
    deploy: 
        runs-on: ubuntu-latest

        env:
            SOLUTION_PATH: ./Showcase/Showcase.sln
            PROJECT_PATH: ./Showcase/Showcase.Web/Showcase.Web.csproj
            PUBLISH_PATH: ${{ github.workspace }}/Showcase/Showcase.Web/bin/Release/net8.0/linux-x64/publish/
            SERVER_PATH: /var/www/showcase/
            SENDGRID_SHOWCASE_KEY: ${{ secrets.SENDGRID_SHOWCASE_KEY }}
            RECAPTCHA_SHOWCASE_KEY: ${{ secrets.RECAPTCHA_SHOWCASE_KEY }}
            SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
            SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
            SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        
        steps:
          - name: Checkout Code
            uses: actions/checkout@v2
    
          - name: Install rsync
            run: sudo apt-get update && sudo apt-get install -y rsync
    
          - name: Setup SSH Key
            run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key && chmod 600 ssh_key
    
          - name: Deploy Files to Server
            run: |
              rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ssh_key" "${{ env.PUBLISH_PATH }}" "${{ env.SERVER_USERNAME }}@${{ env.SERVER_ADDRESS }}:${{ env.SERVER_PATH }}"
    
          - name: Cleanup SSH Private Key File
            run: rm ssh_key