name: pull-request-main

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SOLUTION_PATH: ./Showcase/Showcase.sln

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_PATH }}
    - name: Test
      run: dotnet test --no-build --verbosity normal ${{ env.SOLUTION_PATH }}
